### ISSUE TITLE
TCP keepalive is not activated in client since ver1.3.0

### ISSUE THREAD

**Issue by maladen** [mz-automation/libiec61850#115]
IedConnection.ConnectionClosedHandler is not invoked in the dotnet client examples in current version of the library. 
I've done some research comparing with v.1.2.2 and found out that in hal\socket\win32\socket_win32.c in ver. 1.3.x we should call Socket_activateTcpKeepAlive in Socket_connect() and then IedConnection.ConnectionClosedHandler will be invoked on server disconnect.

The same problem is valid for hal\socket\linux\socket_linux.c but i still haven't figured out how to correct it.

**Comment by mzillgith** [comment]
I changed the title. I guess this is more accurate. You are right in the v1.3 implementation the Socket_activateTcpKeepAlive is called in the wrong place because the client side "native" sockets will only be created when Socket_connect is called. I changed this so that the sockets are created when the TcpSocket_create function is called. This way the TCP keep alive activation works.

**Comment by maladen** [comment]
Hello,
after compiling and testing the fixed version now I get 
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
when calling IedConnection_connect on Windows platform.

It works on Linux!

**Comment by mzillgith** [comment]
Oops. I pushed before testing it on Windows. Thanks for the hint. Now it seems to work.
