### ISSUE TITLE
[C#] Control Operate (MMS_FLOAT) (CAUSE_UNKNOWN)

### ISSUE THREAD

**Issue by IgorMundstein** [mz-automation/libiec61850#41]
Hi,

I have already been able to use the operation method on **boolean**, **integer** and **bit_string** control points.
I am trying to use the command operate for **float** point. But, I am getting an error.

**Model: DIRECT_NORMAL**
![image](https://user-images.githubusercontent.com/3512138/33984473-e2e120b2-e09e-11e7-9ed4-5c6df2218898.png)

**[Code]**
```
IedConnection connection = new IedConnection();
connection.Connect("192.168.0.108", 102);

ControlObject control = connection.CreateControlObject("Xtorm_ServerLogicalDevice/YEFN1.ColPos");
control.SetOrigin("192.168.0.249", OrCat.REMOTE_CONTROL);

MmsValue value = new MmsValue(1.0f);
bool isOperated = control.Operate(value);

LastApplError result = control.GetLastApplError();
```

**The Operate method returns: false**
![image](https://user-images.githubusercontent.com/3512138/33984601-60d340ae-e09f-11e7-8602-cac3ed6a0ee4.png)

**Wireshark:**
![image](https://user-images.githubusercontent.com/3512138/33988410-7528b2e4-e0ab-11e7-8004-1d5b15b2f860.png)

![image](https://user-images.githubusercontent.com/3512138/33984687-ae5070b8-e09f-11e7-889f-0a262ccf2629.png)

![image](https://user-images.githubusercontent.com/3512138/33984708-babff526-e09f-11e7-9874-bad0d93c7357.png)

![image](https://user-images.githubusercontent.com/3512138/33984714-bd05a48e-e09f-11e7-987d-864d66d6df61.png)

**Am I doing something wrong?**

**Comment by mzillgith** [comment]
Hi,
the response "object-access-denied" is misleading. I think the reason is that the client is sending a wrong "ctlVal". The "ctlVal" for APC CDC has to be of type "structure" with a single "float" element. In the wireshark screenshot it looks as only a "float" is send for "ctlVal". The conversion from "float" to the "structure" type shoudl be done by the library automatically if a "float" is provided to the Operate method. But it seems the detection of APC has been removed by some past refactoring. I will add it again to fix the problem.

**Comment by IgorMundstein** [comment]
@mzillgith 

I agree. The value structure is incorrect.

**I did a sample image:**

![image](https://user-images.githubusercontent.com/3512138/33997181-b6e01186-e0ca-11e7-81ba-dc817121a1b7.png)

Let me know when you make the correction.

Thanks!

**Comment by mzillgith** [comment]
The problem should be fixed now. You have to recompile the native library.

**Comment by IgorMundstein** [comment]
Bug has been fixed.

Thank you.
