### ISSUE TITLE
Support for VSS (Visible String Status) and VSG (Visible String Setting) CDC types 

### ISSUE THREAD

**Issue by matsepahi** [mz-automation/libiec61850#42]
Hi,
We represent some status values of our device as visible strings. But corresponding CDC types are not available yet in your library. Are there any plans to implement them in near future?

**Comment by mzillgith** [comment]
Hi,
As far as I see there are no restrictions of CDC types you can implement with the library with any of the supported methods to generate a data model. What exact problem did you encounter?

**Comment by matsepahi** [comment]
I want to add data objects of types VSS and VSG to a logical node. Following the documentations and examples available for other CDC types, it is expected to be done by calling functions CDC_VSS_create and CDC_VSG_create. But these functions are missing and I can't find any straightforward alternatives.

**Comment by mzillgith** [comment]
Ok. I see what you mean. The usual way I do is to generate the data model code from the ICD/SCL file with the tools in the toos/model_generator folder. There are different options. One  option is to use the gendyncode.jar tool to generate template code for the LN types or DO types found in the SCL file. The functions you mentioned were more intended as helper functions but for me they turned out not to be very useful. For convenience I added the two functions you were asking for.

**Comment by matsepahi** [comment]
There isn't any ICD/SCL files in our project. Our nodes are dynamic and these functions are vital. Thanks for adding them. It was a great help.
Best Wishes.
