### ISSUE TITLE
IedServer_update*AttributeValue segmentation fault

### ISSUE THREAD

**Issue by davideandreuzza** [mz-automation/libiec61850#52]
When I try to update the value of a DataAttribute inside an Oper Object, the library goes into segmentation fault. Probably what I am trying to do is not so widely used, but could you consider not to crash the application?
Just to detail more my problem, let's assume I want to update a boolean ctlVal. The problem is inside `IedServer_updateBooleanAttributeValue`, when `MmsValue_getBoolean` is called.

**Comment by mzillgith** [comment]
Hello,
The attributes in "Oper" or other control model related objects are handled by the protocol library internally. They cannot be accessed by some of the IedServer_updateAttributeValue functions as the DataAttribute objects don't have an internal reference to the values. There is also no good reason to do so. What can be done is to do a NULL pointer check in the function and then silently ignore the function call. But I am not sure to do that because it would only hide some problem in the application.

**Comment by davideandreuzza** [comment]
I get your point. Maybe you can add some debug information, so that one can understand why the library goes into segmentation fault. Thank you very much.
