### ISSUE TITLE
[Question] [C#] Connection

### ISSUE THREAD

**Issue by IgorMundstein** [mz-automation/libiec61850#55]
Hi,

I have doubts about connection.

1 - When the ConnectionClosedHandler method is called. Do I have to call some IedConnection method? Like (Abort, Release, Close and Dispose)

2 - When an IedConnectionException throws with IedClientError like (IED_ERROR_NOT_CONNECTED, IED_ERROR_CONNECTION_LOST, IED_ERROR_CONNECTION_REJECTED). Do I have to call some IedConnection method? Like (Abort, Release, Close and Dispose)

3 - We have 4 methods to close connection (Abort, Release, Close and Dispose). Can I call all methods? Is there a call order? Like (Release, Abort, Close, Dispose)

I read the documentation (http://libiec61850.com/csharp-api/class_i_e_c61850_1_1_client_1_1_ied_connection.html) about each method. However, I did not understand very well.

**Comment by mzillgith** [comment]
Hi,
1) The ConnectionClosedHandler is only for information that the connection is closed. You don't have to call any of these functions.
2) No, in this case you also don't have to call these functions because the connection is already closed (or was never opened). You might only call the Dispose method to release the native resources. But this is not required because the garbage collector will do for you.
3) All these function can be used to close the connection. You should only call one of them. Dispose will implicitly call Close. Close is very "rude" because it simply closes the TCP connection while Abort and Release send the appropriate MMS messages before they close the connection and are more standard compliant.

**Comment by IgorMundstein** [comment]
I got it.

Thx Michael.
