### ISSUE TITLE
[C#] [Question] GetLogicalNodeDirectory with ACSIClass.ACSI_CLASS_DATA_SET multiple repeated requests?

### ISSUE THREAD

**Issue by IgorMundstein** [mz-automation/libiec61850#89]
Hi Michael @mzillgith 

A doubt.

The parameter (logicalNodeName) passed to the method is the LD / LN and ACSIClass.ACSI_CLASS_DATA_SET. However, in wireshark multiple requests are repeated only with the logical device. This happens because a request is created for each logical node. Is it right?

![image](https://user-images.githubusercontent.com/3512138/48645164-00c04180-e9cc-11e8-8662-37920aad8e80.png)
![image](https://user-images.githubusercontent.com/3512138/48645179-09187c80-e9cc-11e8-9ea6-06aae04ac713.png)

![image](https://user-images.githubusercontent.com/3512138/48645187-103f8a80-e9cc-11e8-8ea7-45353e72a353.png)
![image](https://user-images.githubusercontent.com/3512138/48645209-20576a00-e9cc-11e8-9502-1a51bfca3639.png)

![image](https://user-images.githubusercontent.com/3512138/48645632-652fd080-e9cd-11e8-864b-5cf759c0f808.png)
![image](https://user-images.githubusercontent.com/3512138/48645644-6cef7500-e9cd-11e8-9b35-b35b28cfe362.png)

![image](https://user-images.githubusercontent.com/3512138/48646540-53036180-e9d0-11e8-96ce-a47b4c8ac2c2.png)
![image](https://user-images.githubusercontent.com/3512138/48646548-57c81580-e9d0-11e8-8400-75f630ef36e9.png)

![image](https://user-images.githubusercontent.com/3512138/48646560-5c8cc980-e9d0-11e8-9f27-cb3385465be5.png)
![image](https://user-images.githubusercontent.com/3512138/48646567-6282aa80-e9d0-11e8-99bd-1f1ada760505.png)

**Comment by mzillgith** [comment]
Hi,
The problem is that MMS does not allow to request for data sets of a specific logical node (MMS does not even know logical nodes). So the MMS get name list call will always return all data sets of a logical device. In order for the API to be similar to the ACSI services the GetLogicalNodeDirectory function has been implemented as it is: request the data sets of the logical device and filter the results to only return the data set of the logical node.
I am thinking about adding another API function so that this can be optimized (or cache the first result for the next calls).

**Comment by IgorMundstein** [comment]
Hi,

Exactly. However, the parameter passed to the method is the logical node and not the logical device. It would be interesting to somehow reduce that to just one request. You can create a new method that accepts the logical device as a parameter or you can create some kind of cache in the current method. I am a humble user. It's up to you.
